version: '3'
services:
  backend:
    build:
      context: ./backend   # 設置後端應用程式的 Dockerfile 路徑
    ports:
      - "80:80"            # 映射後端應用程式的端口
    depends_on:
      - database           # 如果有需要，可以依賴於其他服務，例如資料庫

  frontend:
    build:
      context: ./frontend  # 設置前端應用程式的 Dockerfile 路徑
    ports:
      - "3001:3001"        # 映射前端應用程式的端口
