version: '3.8'
services:
  backend:
    build:
      context: ./backend   # 設置後端應用程式的 Dockerfile 路徑
    ports:
      - "80:80"            # 映射後端應用程式的端口

  frontend:
    build:
      context: ./frontend  # 設置前端應用程式的 Dockerfile 路徑
    ports:
      - "3001:3001"        # 映射前端應用程式的端口
